In [1]:
# 라이브러리 불러오기
import numpy as np

In [2]:
# Numpy 객체 정보를 확인하기 위한 사용자 함수 정의 : 객체타입, 구조, 차원, 데이터타입
def np_print(arr):
    text="""
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data : \n {}""".format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

## 산술연산

- 더하기 : +, add()
- 빼기 : -, subtract()
- 나누기 : /, divide()
- 곱하기 : *, multiply()
- 지수곱 표현 : exp()
- 제곱근 : sqrt()
- 로그 : log()
- 내적(행렬곱) : dot()

In [6]:
# 1부터 10미만의 범위(지정범위)에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열의 배열
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# 4 이상 13미만의 범위에서 1식 증가하는 숫자를 데이터로 가진 3행 3열 배열 생성
b = np.arange(4, 13).reshape(3, 3)
b

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
# 10 ~ 21까지 3행 4열 형태로 만들기
c = np.arange(10, 22).reshape(3, 4)
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### 더하기
    - 배열 + 배열
    - np.add(arr1, arr2)

In [12]:
# 산술연산자
a + b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [13]:
# np.add(배열1, 배열2)
np.add(a, b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [14]:
# 구조 다른 배열간의 산술연산자 사용시 : 특정 조건을 만족하지 않으면 에러가 납니다.
a + c

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### 빼기

    - 배열 - 배열
    - np.subtract(arr1, arr2)

In [15]:
# 산술연산자
a - b

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [16]:
np.subtract(a, b)

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [18]:
np.subtract(b, a)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

### 나누기

    - 배열 / 배열
    - np.divide(arr1, arr2)

In [19]:
# 산술연산자
a / b

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [20]:
b / a

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

In [21]:
np.divide(a, b)

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [22]:
np.divide(b, a)

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

### 곱하기

    - 배열 * 배열
    - np.multiply(arr1, arr2)

In [24]:
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [26]:
np.multiply(a, b)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

### 제곱근

- np.sqrt(arr)

<img src='img/sqrt.gif' width='400' height='200' align='left'>

In [27]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### 내적(행렬곱)

- np.dot(a, b)

<img src='img/dotProduct.png' width='400' height='200' align='left'>

In [28]:
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [29]:
np.dot(a, b)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

### Numpy 배열 연산

#### 2. 비교 연산

1) 요소

- 값에 대한 비교 : ==, !=
- 크기에 대한 비교 : >, <, >=, <=
    
2) 배열
- 두 배열 전체에 대한 비교 : array_equal(a, b)

In [32]:
print(a)
print(b)

a == b

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [31]:
# 두 배열 요소에 대하여 값이 다른지 비교
a != b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [33]:
# 두 배열이 완전히 일치하는지 여부만 조회
# 하나의 T/F로 반환
np.array_equal(a, b)

False

### Numpy 배열 연산

3. 집계 함수

    - Numpy 배열에 대해 집계 함수를 적용할 때는 반드시 axis로 설정된 기준에 따라 연산 수행
    - 별도로 값을 지정하지 않으면 기본값은 axis = None으로 지정
    - axis
        - axis = None <br>
        전체 데이터를 하나의 배열로 간주하고 집계 함수의 연산 범위를 전체 배열로 지정
        <br>
        <img src='img/axis_None.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 0 <br>
        열을 기준으로 동일한 열에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_0.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 1 <br>
        행을 기준으로 동일한 행에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_1.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
    - 집계 함수 : 배열객체에 대한 메소드로 사용하거나 Numpy 라이브러리의 메소드로 사용하는 두 가지 방법
        - 합계 : sum()
        - 최소값 : min()
        - 최대값 : max()
        - 누적 합계 : cumsum()
        - 평균 : mean()
        - 중앙값 : median()
            - 크기 순으로 나열된 데이터에 대해 중앙에 위치하는 값
        - 상관계수 : corrcoef()
            - 데이터 간의 상관관계를 나타내는 수치(-1 <= r <= 1)
        - 표준편차 : std()
            - 분산의 제곱근, 데이터가 평균으로부터 흩어져 있는 정도
            - 분산 = 편차(요소-전체평균)제곱의 평균
        - 고유값 : unique()

In [34]:
# 사용할 배열 객체 확인
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
# 합계 - 전체 기준 => 모든 요소에 대한 합
# 1) 배열 타입의 메서드 : arr.sum()
# 2) numpy함수 : np.sum(arr)
a.sum()

45

In [36]:
# 합계 - row, 가로축별 합산
# 메서드, np함수의 파라미터값 : axis=1
# 결과값 : [0번row합, 1번row합, 2번row합]
c.sum(axis=1)

array([46, 62, 78])

In [37]:
# 합계 - column, 세로축별 합산 결과
# 메서드, np함수의 파라미터값 : axis=0
# 결과값 : [0번째 column합, 1번째 column합, 2번째 column합 ...]
c.sum(axis=0)

array([42, 45, 48, 51])

In [40]:
# 최소값 - 전체 기준
# 1) 배열 타입의 메서드 : arr.min()
# 2) numpy 함수 : np.min(arr)
c.min()
np.min(c)

10

In [41]:
# (참고) 파이썬 리스트에서 최소값 찾기
x = [1, 2, 3, 4]
min(x)

1

In [42]:
# 최소값 - 각 가로축(row)별 최소값 찾기
# 결과값 : [0번째 row최소값, 1번째 row최소값]
c.min(axis=1)

array([10, 14, 18])

In [43]:
# 최소값 - 각 세로축(column)별 최소값 찾기
# 결과값 : [0번째column최소값, 1번째column최소값]
c.min(axis=0)

array([10, 11, 12, 13])

In [46]:
# 최대값 - 전체 기준
# 1) 배열 타입의 메서드 : arr.max()
# 2) numpy 함수 : np.max(arr)
c.max()
np.max(c)

21

In [47]:
# 최대값 - 가로축 기준(row)
c.max(axis=1)

array([13, 17, 21])

In [48]:
# 최대값 - 세로축 기준
c.max(axis=0)

array([18, 19, 20, 21])

In [49]:
# 누적합계 - 전체 기준
# 1) 배열 타입의 메서드 : arr.cumsum()
# 2) numpy함수 : np.cumsum(arr)
# 결과값 :
c.cumsum()

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145, 165, 186],
      dtype=int32)

In [50]:
# 누적합계 - 가로축(row) 기준
c.cumsum(axis=1)

array([[10, 21, 33, 46],
       [14, 29, 45, 62],
       [18, 37, 57, 78]], dtype=int32)

In [51]:
c.cumsum(axis=0)

array([[10, 11, 12, 13],
       [24, 26, 28, 30],
       [42, 45, 48, 51]], dtype=int32)

In [52]:
# 평균 - 전체데이터 기준
# 1) 배열 타입의 메서드 : arr.mean()
# 2) numpy 함수 : np.mean(arr)
c.mean()

15.5

In [53]:
# 평균 - 가로축 기준
c.mean(axis=1)

array([11.5, 15.5, 19.5])

In [54]:
# 평균 - 세로축 기준
c.mean(axis=0)

array([14., 15., 16., 17.])

In [55]:
# 중앙값 - 전체 기준
# numpy 함수 : np.median(arr)
# arr.median()을 직접호출할수없음
np.median(c)

15.5

In [56]:
# a를 가지고(개) 중앙값을 구하면 원본에 있는 숫자로 잡힙니다.
print(np.median(a))
print(a)

5.0
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
# 중앙값 - 가로축 기준
np.median(c, axis=1)

array([11.5, 15.5, 19.5])

In [61]:
# 중앙값 - 세로축 기준
np.median(c, axis=0)

array([14., 15., 16., 17.])

In [62]:
# 상관계수 : 두 데이터간의 상관관계(양/음의 상관관게)
# numpy 함수 : np.corrcoef(arr1, arr2)
x = np.array([163, 175, 181, 155, 157, 167, 178, 170])
y = np.array([52, 70, 69, 48, 43, 70, 81, 75])

In [63]:
np.corrcoef(x, y)

array([[1.        , 0.85607253],
       [0.85607253, 1.        ]])

In [64]:
# 표준편차 - 전체 데이터 기준
# 1) 배열타입 메서드 : arr.std()
# 2) numpy 함수 : np.std(arr)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
a.std()

2.581988897471611

In [66]:
# 표준편차 - row기준(가로줄 기준)
a.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [68]:
a.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [69]:
# 고유값 : 전체 값에 적용
# numpy 함수 : np.unique(arr)
np.unique(c)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [70]:
# 중복된 요소를 1개로 쳐서 해당 배열에 어떤 유형의 데이터가 있는지 보여줌
np.unique(np.array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]))

array([1, 2, 3])

In [75]:
# 난수 패턴 고정
np.random.seed(1000)

In [76]:
# 0이상 3이하의 정수 값을 가지는 3행 3열 배열 생성
# hint : randint를 쓰세요
d = np.random.randint(0, 4, size=(3, 3))
d

array([[3, 3, 3],
       [0, 3, 2],
       [0, 1, 1]])

In [77]:
np.unique(d)

array([0, 1, 2, 3])

In [79]:
# 고유값 - 가로축(row기준)
np.unique(d, axis=1)

array([[3, 3, 3],
       [0, 2, 3],
       [0, 1, 1]])

In [80]:
# 고유값 - 세로축(column기준)
np.unique(d, axis=0)

array([[0, 1, 1],
       [0, 3, 2],
       [3, 3, 3]])

#### 브로드캐스팅(BroadCasting)

- 서로 다른 구조(shape)를 가진 배열에 대해 연산을 수행할 때 구조를 맞추는 과정
- 배열과 스칼라값 간의 연산
- 배열과 배열 간의 연산
- 브로드캐스팅 규칙 ; 축의 길이가 일치하거나 둘 중 하나의 길이가 1인 두 배열에 대해 호환성을 가짐
<img src='img/broadcast.png' width='600' height='400' align='left'>

In [81]:
# 사용할 배열 객체 다시 확인
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 1. 배열의 값(single value, scala)

- 스칼라 값을 배열의 구조와 동일한 배열로 변형하여 연산 수행

In [82]:
# 구조가 다른 배열간의 연산
# a배열의 모든 요소에 각각 10씩 더하기
a + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [86]:
# 스칼라 -> 배열 변형
# 3행 3열 구조에 모든 요소가 10인 배열 요소 생성
scalar_arr = np.full_like(a, 10) # a가 3 * 3 형태인데 그 형태에 내부 값
np_print(scalar_arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [85]:
# 스칼라값을 직접 더하나 아니면 해당 숫자가 들어간 배열을 만들어 더하나 차이가 없음
a + scalar_arr

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

#### 2. 서로 다른 구조의 배열

- 행, 열의 최대 길이를 기준으로 구조를 생성한 배열로 변형하여 연산 수행
- 확장된 행, 열에 대해서 기존 배열과 동일한 데이터로 구성

In [91]:
# 1행 4열의 구조에서 1, 2, 3, 4를 값으로 가지는 배열 x 생성
# 4행 1열의 구조에서 1, 2, 3, 4를 값으로 가지는 배열 y 생성

x = np.arange(1, 5).reshape(1, 4)

y = np.arange(1, 5).reshape(4, 1)

In [92]:
x

array([[1, 2, 3, 4]])

In [93]:
y

array([[1],
       [2],
       [3],
       [4]])

In [96]:
# 배열 x를 동일한 값으로 4행으로 확장한 새로운 배열 생성
# 행방향으로 배열 추가하기(세로길이 증가) 메서드 : np.append(arr1, arr2, aixs=0)
new_x = np.append(x, x, axis=0)
new_x

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [97]:
# new_x를 이용해 4 * 4 형태 배열로 만들어 new_x에 저장해주세요.
new_x = np.append(new_x, new_x, axis=0)
new_x

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [101]:
# y를 이용해서도 4 * 4 형태로 만들어주세요 (new_y 변수에 저장)
new_y = np.append(y, y, axis=1)
new_y = np.append(new_y, new_y, axis=1)
new_y

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [102]:
# 1행 4열과, 4행 1열 배열의 브로드캐스팅 연산
x + y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [103]:
# 4행 4열로 확장시킨 new_x + new_y 덧셈과 차이가 없음
new_x + new_y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

### 벡터 연산

- 요소들에 대한 연산을 벡터 연산으로 처리하면 일반적인 for반복문으로 연산 작업을 처리하는 것보다 월등히 
뛰어난 처리 속도로 효율적인 작업가능

In [105]:
# 0부터 시작해서 100000000개 요소를 가진 배열 생성
x = np.arange(100000000)
x

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [116]:
%%time
# 해당 셀을 완전히 수행하는데 소요된 시간을 표시해주는 주피터노트북 명령어
# 셀의 가장 상단에 위치해야함(주석 포함해서도 가장 상단에 위치해야함)

# 반복문을 통한 합계 (x변수에 저장한 넘파이 배열 자료 총합 구하기)
# 시간단위 : 1s = 1,000ms(밀리세컨드) = 1,000,000us(마이크로세컨드)
loop_result = 0 # 0 ~ 99999999 총합을 저장할 변수

for i in x:
    loop_result += i
loop_result

<timed exec>:9: RuntimeWarning: overflow encountered in long_scalars


KeyboardInterrupt: 

In [119]:
%%time
# 넘파이 배열에서 총합구하는 명령어로 구하고 수행시간을 측정해보세요.
np.sum(x)

CPU times: total: 62.5 ms
Wall time: 61.1 ms


887459712